#!/bin/sh
. "$(dirname "$0")/_/husky.sh"

#!/usr/bin/env bash
LC_ALL=C
local_branch=“$(git rev-parse --abbrev-ref HEAD)”
master="master"
main="main"
if [ $local_branch != $master -a $local_branch != $main ]
then
  echo “GIT 브랜치 이름 ${local_branch}”
  echo “complete commit”
else
  echo “master , main 브랜치에서는 commit 할 수 없습니다.”
  exit 1 //에러
fi
